In [332]:
import numpy as np

In [335]:
numbers_file = open('numbers2.txt','r')
numbers = numbers_file.readline().split(',')
numbers = [int(i) for i in numbers]
print("Numbers : ")
print(numbers)
print(len(numbers))

grids_file = open('input2.txt','r')
tables = []
table = []
count = 1
while True:
    line = grids_file.readline()
    if not line:
        break
    k = line.rstrip().split(' ')
    if len(k) == 1:
        continue
    temp = []
    for i in k:
        if i.isdigit() :
            temp.append(int(i))
    table.append(temp)
    count += 1
    if count > 5 :
        a = table.copy()
        tables.append(a)
        count = 1
        table.clear()
tables = np.array(tables)
print("All Tables : ")
print(tables)

lines = np.negative(np.ones((tables.shape[0],5,5)))
columns = np.copy(lines)

found = False
val = -1
bingo = []
bingo_indexes = []
for n in numbers:
    indexes = np.argwhere(tables == n)
    for index in indexes :
        lines[index[0]][index[1]][index[2]] = n
        columns[index[0]][index[2]][index[1]] = n
        for line,column in zip(lines,columns):
            for l,c in zip(line,column):
                if (-1 not in l) or (-1 not in c):
                    if (-1 not in l):
                        bingo = np.copy(l)
                    else:
                        bingo = np.copy(c)
                    val = n
                    bingo_indexes = np.copy(index)
                    bingo_indexes = np.delete(bingo_indexes,2)
                    found = True
                    break
            if found:
                break
    if found:
        break

print("Bingo Value : " + str(val))
print("Bingo line/column : ")
print(bingo)
# print(bingo_indexes)
bingo_table = np.copy(tables[bingo_indexes[0]])
print("Bingo table : ")
print(bingo_table)

for n in range(numbers.index(val) + 1):
    indexes = np.argwhere(bingo_table == numbers[n]).ravel()
    if not len(indexes):
        continue
    print(indexes)
    bingo_table[indexes[0]][indexes[1]] = 0
print(bingo_table)
sum = bingo_table.sum()
print("sum = " + str(sum))
score = sum * val
print("Score = " + str(score))




Numbers : 
[17, 2, 33, 86, 38, 41, 4, 34, 91, 61, 11, 81, 3, 59, 29, 71, 26, 44, 54, 89, 46, 9, 85, 62, 23, 76, 45, 24, 78, 14, 58, 48, 57, 40, 21, 49, 7, 99, 8, 56, 50, 19, 53, 55, 10, 94, 75, 68, 6, 83, 84, 88, 52, 80, 73, 74, 79, 36, 70, 28, 37, 0, 42, 98, 96, 92, 27, 90, 47, 20, 5, 77, 69, 93, 31, 30, 95, 25, 63, 65, 51, 72, 60, 16, 12, 64, 18, 13, 1, 35, 15, 66, 67, 43, 22, 87, 97, 32, 39, 82]
100
All Tables : 
[[[10 27 53 91 86]
  [15 94 47 38 61]
  [32 68  8 88  9]
  [35 84  3  7 87]
  [62 78 90 66 64]]

 [[30 51 26 16 57]
  [66 88 47 75 23]
  [61 77 64  9 73]
  [44 32 28 80 81]
  [ 3 99 67 49 78]]

 [[68 92 82 74 83]
  [12 99 80 72  3]
  [56 96 36 28 43]
  [ 2  7 14 24  9]
  [63 76 40 37 73]]

 ...

 [[19 18 55 70 84]
  [28 68 71 20  6]
  [27 90 86 52  2]
  [44 43 15 48 39]
  [14 37 63 83 75]]

 [[73 61 41 96 68]
  [89 40 53 12 91]
  [29 37 59 10 19]
  [69 98 88 82 24]
  [65 72 25 42  4]]

 [[62 50 34 16  8]
  [75 88 84 33 29]
  [ 2 64 31 41 86]
  [94 45 76 70  3]
  [39 89 66  

In [334]:
# print("All Tables : ")
# print(tables)
print(numbers)

lines = np.negative(np.ones((tables.shape[0],5,5)))
columns = np.copy(lines)

found = False
val = -1
bingo = []
bingo_indexes = []
winning_tables = dict.fromkeys(np.arange(len(tables)))

for k in range(len(tables)) :
    winning_tables[k] = []
print(winning_tables)

for i in range(len(tables)):
    found = False
    for n in numbers:
        indexes = np.argwhere(tables[i] == n).ravel()
        winning_tables[i].append(n)
        if len(indexes):
            lines[i][indexes[0]][indexes[1]] = n
            columns[i][indexes[1]][indexes[0]] = n
        for l,c in zip(lines[i],columns[i]):
            if (-1 not in l) or (-1 not in c):
                found = True
                break
        if found:
            break   
print(winning_tables)

lens = []
for k in winning_tables.keys() :
    lens.append(len(winning_tables[k]))
print(lens)

print(max(lens))
maxes_indexes = [i for i,val in enumerate(lens) if val==max(lens)]
max_ind = max(maxes_indexes)
print(maxes_indexes)
print(max_ind)


val = winning_tables[max_ind][-1]

print("Bingo Value : " + str(val))

bingo_table = np.copy(tables[max_ind])
print("Bingo table : ")
print(bingo_table)


for n in range(numbers.index(val) + 1):
    indexes = np.argwhere(bingo_table == numbers[n]).ravel()
    if not len(indexes):
        continue
    bingo_table[indexes[0]][indexes[1]] = 0
print(bingo_table)
sum = bingo_table.sum()
print("sum = " + str(sum))
score = sum * val
print("Score = " + str(score))



[17, 2, 33, 86, 38, 41, 4, 34, 91, 61, 11, 81, 3, 59, 29, 71, 26, 44, 54, 89, 46, 9, 85, 62, 23, 76, 45, 24, 78, 14, 58, 48, 57, 40, 21, 49, 7, 99, 8, 56, 50, 19, 53, 55, 10, 94, 75, 68, 6, 83, 84, 88, 52, 80, 73, 74, 79, 36, 70, 28, 37, 0, 42, 98, 96, 92, 27, 90, 47, 20, 5, 77, 69, 93, 31, 30, 95, 25, 63, 65, 51, 72, 60, 16, 12, 64, 18, 13, 1, 35, 15, 66, 67, 43, 22, 87, 97, 32, 39, 82]
{0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: [], 13: [], 14: [], 15: [], 16: [], 17: [], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [], 26: [], 27: [], 28: [], 29: [], 30: [], 31: [], 32: [], 33: [], 34: [], 35: [], 36: [], 37: [], 38: [], 39: [], 40: [], 41: [], 42: [], 43: [], 44: [], 45: [], 46: [], 47: [], 48: [], 49: [], 50: [], 51: [], 52: [], 53: [], 54: [], 55: [], 56: [], 57: [], 58: [], 59: [], 60: [], 61: [], 62: [], 63: [], 64: [], 65: [], 66: [], 67: [], 68: [], 69: [], 70: [], 71: [], 72: [], 73: [], 74: [], 75: [], 76: [], 77