In [127]:
import numpy as np

In [128]:
numbers_file = open('numbers.txt','r')
numbers = numbers_file.readline().split(',')
numbers = [int(i) for i in numbers]

grids_file = open('input.txt','r')
tables = []
table = []
count = 1
while True:
    line = grids_file.readline()
    if not line:
        break
    k = line.rstrip().split(' ')
    if len(k) == 1:
        continue
    temp = []
    for i in k:
        if i.isdigit() :
            temp.append(int(i))
    table.append(temp)
    count += 1
    if count > 5 :
        a = table.copy()
        tables.append(a)
        count = 1
        table.clear()
tables = np.array(tables)
print(tables)
lines = np.negative(np.ones((3,5,5)))
print(lines)


[[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8  7 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3  7]]]
[[[-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]]

 [[-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]]

 [[-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]
  [-1. -1. -1. -1. -1.]]]
